(defun allowed-moves (board player i j)
  (let ((diagonal-left (1- j))
        (diagonal-right (1+ j))
        (moves '()))
    (when (and (> i 0) (> diagonal-left 0)
               (or (null (aref board (1- i) (1- j)))
                   (eql (aref board (1- i) (1- j)) player)))
      (push (list (list i j) (list (1- i) (1- j)) player) moves))
    (when (and (> i 0) (< diagonal-right 8)
               (or (null (aref board (1- i) (1+ j)))
                   (eql (aref board (1- i) (1+ j)) player)))
      (push (list (list i j) (list (1- i) (1+ j)) player) moves))
    moves))
